Repository JuliaVersionControl/GitCommand.jl, pull requests merged in 2021-03, with the labels that each got.

#45 Use `addenv` to ensure git commands don't leak env variables
  Project.toml
  README.md
  src/git.jl
  test/runtests.jl
Labels: bug fix

#47 Fix CI badges in the README
  README.md
Labels: documentation

#51 [breaking] Remove a deprecated function
  Project.toml
  src/git.jl
  src/repl.jl
  test/runtests.jl
Labels: breaking change

#56 Add a docstring
  src/git.jl
Labels: documentation
